### PR TITLE
Versioning and bug squashing

### LINKED ISSUE #98: Release Tracking
Github action pin items to keep version of the database. Create micro releases with time stamps. Website needs to track release number and display it on the page and pass to downloadable sheets.

### PR DESCRIPTION
**Pull request by Will-Cooper**
Closes #98

### CODE REVIEW

**Comment by kelle** [comment]
I'm not sure of the best way to review this. Can we "deploy" it so I can see what it looks like without having to do it locally?

**Comment by Will-Cooper** [comment]
Alas, heroku has stopped working for us nicely :( I could send screengrabs to slack perhaps?

**Comment by kelle** [comment]
I'm happy with screengrabs!  Either here or on Slack.

Do you know why Heroku has stopped? Do we need to pay?

**Comment by Will-Cooper** [comment]
Screenshot from 2022-10-19 17-56-30

**Comment by kelle** [comment]
Love the version number and date but I think the description is too much.

**Comment by Will-Cooper** [comment]
Okie dokie @kelle, removed the comment bit. Several other plot changes, mostly colouring and making sure to use adopted values when possible rather than first

**Comment by Will-Cooper** [comment]
Oh and yes, I believe Heroku is doing away with free accounts cc. @dr-rodriguez

**Review by kelle — APPROVED** [review]
Based on a pretty superficial review, this looks good to me. Not sure if we should also have @dr-rodriguez approve.

**Pull request merged**
