### PR TITLE
Using Bootstrap to improve website design

### PR DESCRIPTION
**Pull request by Will-Cooper**
I've fully changed how the website looks now, functionality remains the same.

### CODE REVIEW

**Comment by kelle** [comment]
Is there an easy way to preview the site?

**Comment by Will-Cooper** [comment]
> Is there an easy way to preview the site?

http://obscure-crag-83541.herokuapp.com/

**Comment by kelle** [comment]
Looks great!  

It looks like the nav menu is also being used as the Footer. I'm not a huge fan of that. For now, maybe the footer can just include a link to the github repo. Maybe something like, 
To learn more about SIMPLE and to provide feedback, please visit our github repos. 
- Website repo: [SIMPLE-web](https://github.com/SIMPLE-AstroDB/SIMPLE-web/) 
- Database repo: [SIMPLE-db](https://github.com/SIMPLE-AstroDB/SIMPLE-db/)

**Comment by Will-Cooper** [comment]
Okie dokie, updated the site with a non nav footer

**Review by kelle — APPROVED** [review]
Looks great to me!

**Pull request merged**
